//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppHellRaid.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Exasm = new HashSet<Exasm>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_dep { get; set; }
        public string FIO { get; set; }
        public Nullable<int> ID_jt { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Chef { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Rank { get; set; }
        public string Extent { get; set; }
        public Nullable<bool> EmplEnable { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Job_title Job_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exasm> Exasm { get; set; }
    }
}
