//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppHellRaid.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exasm
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_ex { get; set; }
        public Nullable<int> ID_dis { get; set; }
        public Nullable<int> ID_stud { get; set; }
        public Nullable<int> ID_empl { get; set; }
        public Nullable<int> ID_audit { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<bool> ExamEnable { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
